会場を株式会社インプレスに更新
kitamu57/ichiyasaGitSample pull request #1
Opened 2024-04-25 19:48 UTC by kitamu57

###変更内容
イベント会場を株式会社インプレスに変更しました。

###
インプレスさんが会場を提供してくれることになりました。

2024-04-25 19:50 UTC, lstandroll commented
いい調整ですね。マージしてもいいと思います。

2024-04-25 19:50 UTC, kitamu57 commented
ありがとうございます。こちらでマージしてしまいます。

2024-04-30 07:47 UTC, lstandroll requested changes
ご確認お願いいたします

2024-04-30 07:47 UTC, lstandroll commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社とインプレスの間にスペースは不要でしょうか

2024-04-30 08:11 UTC, kitamu57 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
スペースは不要かと思います。正式表記でもスペースは入っておりませんでした。

2024-04-30 08:26 UTC, lstandroll commented
気になったのはそれくらいです。

2024-04-30 08:29 UTC, lstandroll approved these changes
大丈夫そうでした。アプルーブします。

2024-04-30 08:29 UTC, lstandroll commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ありがとうございます。

2024-04-30 09:01 UTC, lstandroll commented
LGTM

2024-04-30 09:04 UTC, merged